version: '3.8'

services: 
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mobile-be
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  api:
    build: .
    container_name: mobile_api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mobile-be?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      FILE_UPLOAD_DIR: /app/uploads
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/dang-phong/Desktop/MyProject/storage:/app/uploads
    networks:
      - app_network

networks:
  app_network:

