version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

  api:
    build: .
    container_name: mobile_api
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mobile-be?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      FILE_UPLOAD_DIR: ${FILE_UPLOAD_DIR}
      SECRET: ${SECRET}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/phongdev/app/storage:/app/uploads
    networks:
      - app_network


  nginx:
    image: nginx:latest
    container_name: nginx-reverse
    ports:
      - "80:80"
    volumes:
      - /home/phongdev/app/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - app_network

networks:
  app_network:

