services:
  app:
    extends:
      file: docker-compose.app.yml
      service: app
  mysql:
    extends:
      file: docker-compose.mysql.yml
      service: mysql
  redis:
    extends:
      file: docker-compose.redis.yml
      service: redis
  neo4j:
    extends:
      file: docker-compose.neo4j.yml
      service: neo4j
