services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: pro
    volumes:
      - ${FIREBASE_CONFIG}:/app/config/firebase.json:ro
      - ${STORAGE_PATH}:/app/storage
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
