services:
  app:
    extends:
      file: docker-compose.app.yaml
      service: app
  mysql:
    extends:
      file: docker-compose.mysql.yaml
      service: mysql
  redis:
    extends:
      file: docker-compose.redis.yaml
      service: redis
  neo4j:
    extends:
      file: docker-compose.neo4j.yaml
      service: neo4j

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  neo4j_data:
    driver: local

networks:
  app_network:
    driver: bridge
